### PR TITLE
Update NovaGmap.php

### PR DESCRIPTION
**Pull request by atagadtad**
updated to use Laravel 8's helper methods

### CODE REVIEW

**Review by adamcmoore — APPROVED** [review]
Thanks @atagadtad - approved and merged.

**Comment by AubreyHewes** [comment]
@adamcmoore It seem's this has not actually been merged yet? (only approved)

**Comment by adamcmoore** [comment]
> @adamcmoore It seem's this has not actually been merged yet? (only approved)

Must have been a busy day!

Now merged and tagged as a [new version v1.1](https://github.com/adamcmoore/nova-gmap/releases/tag/v1.1)

**Comment by AubreyHewes** [comment]
Sidenote: maybe it should have had a major bump as it is no longer compatible with old laravel using ^1.0 semver

**Comment by adamcmoore** [comment]
> Sidenote: maybe it should have had a major bump as it is no longer compatible with old laravel using ^1.0 semver

Totally agree. Re-released as v2.0.

**Pull request merged**
